# Database Configuration
quarkus:
  http:
    port: 8080
  dev:
    hot-reload:
      enabled: true
    live-reload:
      enabled: true
  security:
    enabled: true

  datasource:
    db-kind: postgresql
    username: postgres
    password: 4796
    jdbc:
      url: jdbc:postgresql://localhost:5432/user_service_db

  #Hibernate ORM Configuration
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
      #    dialect: org.hibernate.dialect.PostgreSQLDialect

  # JWT Configuration
  smallrye-jwt:
    # JWT configuration settings
    public-key-location: classpath:publicKey.pem
    issuer: your-issuer
    # Additional JWT configuration (optional)
    groups-claim: groups
    path-to-jwt: /path/to/jwt
    # Optional configuration to validate the JWT audience
    audience: your-audience

    # Logging Configuration (Optional)
    quarkus:
      log:
        console:
          level: INFO
        category:
          io:
            quarkus: TRACE

