quarkus:
  http:
    port: 8080

  dev:
    hot-reload:
      enabled: true

    live-reload:
      enabled: true

  datasource:
    db-kind: postgresql
    username: postgres
    password: 4796
    jdbc:
      url: jdbc:postgresql://localhost:5432/user_service_db
    devservices:
      enabled: false  # 🚀 Disable auto Docker-based database creation

  # Hibernate ORM Configuration
  hibernate-orm:
    database:
      generation: drop-and-create
      dialect: org.hibernate.dialect.PostgreSQLDialect

    log:
      sql: true

# JWT Configuration
mp:
  jwt:
    verify:
      issuer: "my-auth-server"

smallrye:
  jwt:
    sign:
      key: "V4g6v6Y3f7s2tBxZy8S5Rrz9EdR5KQ0Qf7IcYH0g7Jk="

# Logging Configuration
  log:
    console:
      level: INFO
    category:
      io:
        quarkus: TRACE
