version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus123
      - POSTGRES_DB=userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - postgres
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/userdb
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=quarkus123
    ports:
      - "8080:8080"

volumes:
  postgres_data: